# Generated by Django 3.2.8 on 2021-11-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
